// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnvwonetzevpwuoawiyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRudndvbmV0emV2cHd1b2F3aXlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NTk4NTEsImV4cCI6MjA1ODIzNTg1MX0.t-6jD-serwHS0og124EB2p5DS49n879r5ZgjXRqXlKw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);